//SCO Content data structure
DATA = {
	arrBlks:[
		block = {
			name:"Course Name 1",
			//28 lessons
			lsnNames:[
			"Lorem ipsum dolor", "Sit amet", "Consectetur adipiscing elit", "Aliquam aliquet vehicula enim", "Sodales malesuada", "Etiam scelerisque efficitur est", "Aenean faucibus consequat", "Nunc eu ultricies", "Aenean in tellus ut lacus", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales", "Lorem ipsum dolor sit amet", "Donec purus eros", "Phasellus pharetra sollicitudin ligula faucibus ullamcorper", "Ut nec felis eu turpis pulvinar pharetra", "Maecenas neque est", "Praesent fringilla id nisi quis rhoncus", "Nam interdum pulvinar risus aliquet pretium"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu.",
				"Pri no unum soleat, te corpora pericula pri, falli voluptua percipit his id. Vis ea ullum expetenda, ad assentior honestatis vel. Vel ne homero dissentiet vituperatoribus, nam ex ancillae assentior vulputate. Facilis docendi adipiscing usu id, epicuri legendos instructior id vis. Vix ex utinam noster, ut qui ipsum nominavi, tale dicit quo eu.",
				"Omnes dictas nam id, in ius tempor placerat definitionem, ex vis intellegebat definitionem. Vel sint maluisset ne, usu cu mundi pericula, has ei impedit ceteros. Sea tempor aliquid officiis at, omnium admodum neglegentur vis ei. Ei propriae prodesset mea, ne eum liberavisse conclusionemque. Luptatum dignissim omittantur et his, ignota repudiare ex mei.",
				"Te omnes deserunt quo, nec id graece alterum. Nec modus doming ut. An pro nominavi noluisse democritum, amet maiorum convenire an has. Partem nostrum intellegebat vel eu.",
				"Ei laudem quodsi quo, sit ut oblique malorum scribentur. Eu ferri dolorum est. Ei cum dico molestiae, no mentitum ocurreret vim, ea per epicuri placerat antiopam. Et tota expetenda efficiantur vim, ne adhuc error duo, soleat eripuit te sea. Vix deleniti lucilius detraxit te, ut summo nonumes vel, eu mea graecis scaevola. Eu sed autem vituperata, per ne malis nostrum.",
				"Ex tation complectitur pro. Ei per perfecto ocurreret. Suas cetero fabellas ad cum, vim ei imperdiet reformidans, id latine tractatos his. Ea quo denique nominati, sed at ullum probatus evertitur. Dicam possim prompta cu vim, quis habeo disputando duo ad, rationibus consequuntur ex mei.",
				"Vix ut impetus petentium accusamus, atqui facilis mea cu. Duo ut splendide scriptorem, at omnis affert mel, ut cum vidit euismod. Vim cu quot ceteros, ad mei liber maiorum. Ex suscipit laboramus suscipiantur cum, qui saepe consulatu ne, eos no veri fabellas. Ei eam probo ocurreret mediocritatem, ea duo purto porro. Te pro errem postulant, per eirmod vidisse at. In eos tamquam malorum.",
				"Mea dicit percipit at, animal volumus mei ex. Id sale aeterno omnesque pri, ut qui legere graeco aperiam. At has reque tamquam. Pri no velit propriae luptatum. Odio legendos ei pri, ex sit quando persecuti.",
				"Illum fuisset ut mei. Vim at debet viderer nusquam, vel soleat intellegat assueverit an. Id duo facilis voluptua corrumpit. Nec ne appareat pertinax, mel utamur consulatu cu. Has an eruditi posidonium referrentur, ut etiam mucius omittam usu, cu partem dictas feugait vim. Alia possit labitur eu mea. Per soleat apeirian eu, mutat cotidieque ne pro, mutat ignota imperdiet eos te.",
				"At est duis imperdiet. An per recusabo assueverit, iriure invenire ea pri. Ad mea platonem repudiare, ad omnes oratio eam. Vix eu atomorum periculis. In vocent disputationi vim, ne integre phaedrum eum. Eu posse urbanitas vix, sea eu movet aeterno.",
				"Eum et molestiae dissentiunt, sit ignota doming viderer ne. Autem maiorum fuisset pri te. Voluptua maiestatis ad sit, purto reprehendunt ex vis. Munere eruditi philosophia quo no.",
				"Cu solet oblique ornatus vim, has etiam malorum noluisse ut, an mea soluta fierent facilisi. No rebum fugit democritum mei, et autem tation ceteros sea, mollis qualisque sed eu. Ut has stet graeco, id cum nobis clita, albucius convenire nam eu. No eam lorem mucius perfecto, ad sed quis wisi labore. Eos paulo repudiandae te. Ne voluptaria ullamcorper pri, graeci accusamus liberavisse ius ut. Copiosae percipit lobortis ex sea, virtute adolescens eum ad.",
				"Lorem ipsum dolor sit amet, eos putant viderer atomorum in, usu erat etiam ei, his an magna choro. Probo antiopam id pro, at probo cotidieque ullamcorper vis. No facilis invenire aliquando duo, dicit eligendi delicata eu sit. Ea laudem soluta praesent his, pri magna petentium ei, ex qui nibh copiosae scribentur. In cum labitur sensibus, vel habeo prompta ne, mei cu nostrum salutatus.",
				"Ad pri molestiae mediocritatem, ponderum scripserit appellantur ad vis. His duis inani facilisis ne, commodo maiestatis vix ei. Pro ut similique omittantur, quem placerat phaedrum mel ex, primis oportere vix eu. Vix nostrum democritum at, cu pri aliquando assueverit dissentiunt, etiam conceptam abhorreant ad nam. Vidit volutpat eam ex, ei nam nihil vocent admodum, in duo affert deleniti probatus.",
				"Qui ut unum posidonium, ad admodum albucius sententiae est. Mel ad paulo minimum, mei ad nonumy instructior. Per molestiae efficiendi ea. Cu eos nonumes conclusionemque, his dolores inciderint ad.",
				"Vim atqui iuvaret et, vel debet nihil ut. Sed ceteros mandamus ne, sit alii soluta noluisse at. Mei cu iusto tamquam. Cu nam adhuc diceret, volutpat incorrupte qui at. Te nec eripuit principes consequat. Facer ornatus quo no, diam impedit sea te.",
				"No regione tincidunt nec. Soleat nusquam mel an, sed assum dicam postulant in, ei mei affert iuvaret percipit. Ignota vocibus reprehendunt has id, vix brute labore neglegentur at. Cu eos dolor dolorum philosophia. Id duis saperet usu, reque sonet sea te, no his case equidem. Ut porro expetenda per, alienum iudicabit eu qui. Et exerci possit aperiam mel.",
				"Est mazim urbanitas posidonium cu, est in libris postulant. Saepe persecuti definitionem sit te, fuisset evertitur ex vim, cu autem percipitur sed. Solet minimum te nec, no quod delenit consulatu his. Ex sed feugait gloriatur, graeco epicuri mediocrem an eam. Ut delectus aliquando mnesarchum mel, dolore sanctus disputando qui at. Et has option officiis aliquando, no per patrioque percipitur intellegebat. Hinc instructior ex duo.",
				"Imperdiet posidonium repudiandae eos ea, vim ne quis adipisci disputando. Usu graece virtute ocurreret te. Nec dolor vocibus adipiscing at. Et qui posse nostro. Animal scripta copiosae mea ad, cum ut vitae alterum, ea mei solet labore dissentiet.",
				"Laudem postea et est. Eos veniam equidem eligendi id, sit at ridens iisque philosophia. Mentitum omnesque antiopam his an, debitis quaestio percipitur duo no, alii probo per id. Sed cu eius minimum, ad clita malorum similique eum. No mel cetero expetenda, eius atomorum his cu. Atomorum mandamus postulant sit eu.",
				"Eum iriure albucius cu, ut esse nostrum quo, est diam omnes no. Eu laoreet incorrupte argumentum est, at usu eleifend senserit. Decore feugait philosophia ne vel. Novum dissentiunt vis no, prompta definitiones vis at. Integre malorum eu est, quot numquam ad est.",
				"Viderer salutatus consequat duo cu, nec timeam interesset id. Ut laoreet maiestatis definitiones est, sit adipiscing cotidieque repudiandae ea. Copiosae principes signiferumque ad ius, nec ei detracto percipit constituto. Has te etiam saepe signiferumque. Ex eos salutandi patrioque.",
				"In sea unum debitis torquatos, sea et repudiare neglegentur. Intellegam assueverit eam te. Usu ea verear inermis, ignota pertinacia et nec. Detracto principes an vis. Vulputate persequeris mea at, tota dicit reprimique est ea."
			],
			lsnDur:[
			"02:52","04:34","54:11","50:34","28:53","43:30","39:13","27:03","01:27","02:55","08:46","52:45","19:10","07:02","12:40","27:01","13:16","51:02","29:10","27:48","40:55","36:06","36:18","37:49","48:31","41:12","05:49","05:56"
			],
		},
		block = {
			name:"Course Name 2",
			//11 lessons
			lsnNames:[
			"Nunc eu ultricies", "Aenean in tellus ut lacus", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu.",
				"Pri no unum soleat, te corpora pericula pri, falli voluptua percipit his id. Vis ea ullum expetenda, ad assentior honestatis vel. Vel ne homero dissentiet vituperatoribus, nam ex ancillae assentior vulputate. Facilis docendi adipiscing usu id, epicuri legendos instructior id vis. Vix ex utinam noster, ut qui ipsum nominavi, tale dicit quo eu.",
				"Omnes dictas nam id, in ius tempor placerat definitionem, ex vis intellegebat definitionem. Vel sint maluisset ne, usu cu mundi pericula, has ei impedit ceteros. Sea tempor aliquid officiis at, omnium admodum neglegentur vis ei. Ei propriae prodesset mea, ne eum liberavisse conclusionemque. Luptatum dignissim omittantur et his, ignota repudiare ex mei."
			],
			lsnDur:[
			"14:19", "07:45", "11:11", "38:45", "29:32", "50:42", "46:43", "55:09", "17:22", "02:55", "50:31"
			]
		},
		block = {
			name:"Course Name 3",
			//31 lessons
			lsnNames:[
			"Consectetur adipiscing elit", "Aliquam aliquet vehicula enim", "Sodales malesuada", "Etiam scelerisque efficitur est", "Aenean faucibus consequat", "Nunc eu ultricies", "Aenean in tellus ut lacus", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu.",
				"Pri no unum soleat, te corpora pericula pri, falli voluptua percipit his id. Vis ea ullum expetenda, ad assentior honestatis vel. Vel ne homero dissentiet vituperatoribus, nam ex ancillae assentior vulputate. Facilis docendi adipiscing usu id, epicuri legendos instructior id vis. Vix ex utinam noster, ut qui ipsum nominavi, tale dicit quo eu.",
				"Omnes dictas nam id, in ius tempor placerat definitionem, ex vis intellegebat definitionem. Vel sint maluisset ne, usu cu mundi pericula, has ei impedit ceteros. Sea tempor aliquid officiis at, omnium admodum neglegentur vis ei. Ei propriae prodesset mea, ne eum liberavisse conclusionemque. Luptatum dignissim omittantur et his, ignota repudiare ex mei.",
				"Te omnes deserunt quo, nec id graece alterum. Nec modus doming ut. An pro nominavi noluisse democritum, amet maiorum convenire an has. Partem nostrum intellegebat vel eu.",
				"Ei laudem quodsi quo, sit ut oblique malorum scribentur. Eu ferri dolorum est. Ei cum dico molestiae, no mentitum ocurreret vim, ea per epicuri placerat antiopam. Et tota expetenda efficiantur vim, ne adhuc error duo, soleat eripuit te sea. Vix deleniti lucilius detraxit te, ut summo nonumes vel, eu mea graecis scaevola. Eu sed autem vituperata, per ne malis nostrum.",
				"Ex tation complectitur pro. Ei per perfecto ocurreret. Suas cetero fabellas ad cum, vim ei imperdiet reformidans, id latine tractatos his. Ea quo denique nominati, sed at ullum probatus evertitur. Dicam possim prompta cu vim, quis habeo disputando duo ad, rationibus consequuntur ex mei.",
				"Vix ut impetus petentium accusamus, atqui facilis mea cu. Duo ut splendide scriptorem, at omnis affert mel, ut cum vidit euismod. Vim cu quot ceteros, ad mei liber maiorum. Ex suscipit laboramus suscipiantur cum, qui saepe consulatu ne, eos no veri fabellas. Ei eam probo ocurreret mediocritatem, ea duo purto porro. Te pro errem postulant, per eirmod vidisse at. In eos tamquam malorum.",
				"Mea dicit percipit at, animal volumus mei ex. Id sale aeterno omnesque pri, ut qui legere graeco aperiam. At has reque tamquam. Pri no velit propriae luptatum. Odio legendos ei pri, ex sit quando persecuti.",
				"Illum fuisset ut mei. Vim at debet viderer nusquam, vel soleat intellegat assueverit an. Id duo facilis voluptua corrumpit. Nec ne appareat pertinax, mel utamur consulatu cu. Has an eruditi posidonium referrentur, ut etiam mucius omittam usu, cu partem dictas feugait vim. Alia possit labitur eu mea. Per soleat apeirian eu, mutat cotidieque ne pro, mutat ignota imperdiet eos te.",
				"At est duis imperdiet. An per recusabo assueverit, iriure invenire ea pri. Ad mea platonem repudiare, ad omnes oratio eam. Vix eu atomorum periculis. In vocent disputationi vim, ne integre phaedrum eum. Eu posse urbanitas vix, sea eu movet aeterno.",
				"Eum et molestiae dissentiunt, sit ignota doming viderer ne. Autem maiorum fuisset pri te. Voluptua maiestatis ad sit, purto reprehendunt ex vis. Munere eruditi philosophia quo no.",
				"Cu solet oblique ornatus vim, has etiam malorum noluisse ut, an mea soluta fierent facilisi. No rebum fugit democritum mei, et autem tation ceteros sea, mollis qualisque sed eu. Ut has stet graeco, id cum nobis clita, albucius convenire nam eu. No eam lorem mucius perfecto, ad sed quis wisi labore. Eos paulo repudiandae te. Ne voluptaria ullamcorper pri, graeci accusamus liberavisse ius ut. Copiosae percipit lobortis ex sea, virtute adolescens eum ad.",
				"Lorem ipsum dolor sit amet, eos putant viderer atomorum in, usu erat etiam ei, his an magna choro. Probo antiopam id pro, at probo cotidieque ullamcorper vis. No facilis invenire aliquando duo, dicit eligendi delicata eu sit. Ea laudem soluta praesent his, pri magna petentium ei, ex qui nibh copiosae scribentur. In cum labitur sensibus, vel habeo prompta ne, mei cu nostrum salutatus.",
				"Ad pri molestiae mediocritatem, ponderum scripserit appellantur ad vis. His duis inani facilisis ne, commodo maiestatis vix ei. Pro ut similique omittantur, quem placerat phaedrum mel ex, primis oportere vix eu. Vix nostrum democritum at, cu pri aliquando assueverit dissentiunt, etiam conceptam abhorreant ad nam. Vidit volutpat eam ex, ei nam nihil vocent admodum, in duo affert deleniti probatus.",
				"Qui ut unum posidonium, ad admodum albucius sententiae est. Mel ad paulo minimum, mei ad nonumy instructior. Per molestiae efficiendi ea. Cu eos nonumes conclusionemque, his dolores inciderint ad.",
				"Vim atqui iuvaret et, vel debet nihil ut. Sed ceteros mandamus ne, sit alii soluta noluisse at. Mei cu iusto tamquam. Cu nam adhuc diceret, volutpat incorrupte qui at. Te nec eripuit principes consequat. Facer ornatus quo no, diam impedit sea te.",
				"No regione tincidunt nec. Soleat nusquam mel an, sed assum dicam postulant in, ei mei affert iuvaret percipit. Ignota vocibus reprehendunt has id, vix brute labore neglegentur at. Cu eos dolor dolorum philosophia. Id duis saperet usu, reque sonet sea te, no his case equidem. Ut porro expetenda per, alienum iudicabit eu qui. Et exerci possit aperiam mel.",
				"Est mazim urbanitas posidonium cu, est in libris postulant. Saepe persecuti definitionem sit te, fuisset evertitur ex vim, cu autem percipitur sed. Solet minimum te nec, no quod delenit consulatu his. Ex sed feugait gloriatur, graeco epicuri mediocrem an eam. Ut delectus aliquando mnesarchum mel, dolore sanctus disputando qui at. Et has option officiis aliquando, no per patrioque percipitur intellegebat. Hinc instructior ex duo.",
				"Imperdiet posidonium repudiandae eos ea, vim ne quis adipisci disputando. Usu graece virtute ocurreret te. Nec dolor vocibus adipiscing at. Et qui posse nostro. Animal scripta copiosae mea ad, cum ut vitae alterum, ea mei solet labore dissentiet.",
				"Laudem postea et est. Eos veniam equidem eligendi id, sit at ridens iisque philosophia. Mentitum omnesque antiopam his an, debitis quaestio percipitur duo no, alii probo per id. Sed cu eius minimum, ad clita malorum similique eum. No mel cetero expetenda, eius atomorum his cu. Atomorum mandamus postulant sit eu.",
				"Eum iriure albucius cu, ut esse nostrum quo, est diam omnes no. Eu laoreet incorrupte argumentum est, at usu eleifend senserit. Decore feugait philosophia ne vel. Novum dissentiunt vis no, prompta definitiones vis at. Integre malorum eu est, quot numquam ad est.",
				"Viderer salutatus consequat duo cu, nec timeam interesset id. Ut laoreet maiestatis definitiones est, sit adipiscing cotidieque repudiandae ea. Copiosae principes signiferumque ad ius, nec ei detracto percipit constituto. Has te etiam saepe signiferumque. Ex eos salutandi patrioque.",
				"In sea unum debitis torquatos, sea et repudiare neglegentur. Intellegam assueverit eam te. Usu ea verear inermis, ignota pertinacia et nec. Detracto principes an vis. Vulputate persequeris mea at, tota dicit reprimique est ea.",
				"Imperdiet posidonium repudiandae eos ea, vim ne quis adipisci disputando. Usu graece virtute ocurreret te. Nec dolor vocibus adipiscing at. Et qui posse nostro. Animal scripta copiosae mea ad, cum ut vitae alterum, ea mei solet labore dissentiet.",
				"Laudem postea et est. Eos veniam equidem eligendi id, sit at ridens iisque philosophia. Mentitum omnesque antiopam his an, debitis quaestio percipitur duo no, alii probo per id. Sed cu eius minimum, ad clita malorum similique eum. No mel cetero expetenda, eius atomorum his cu. Atomorum mandamus postulant sit eu.",
				"Eum iriure albucius cu, ut esse nostrum quo, est diam omnes no. Eu laoreet incorrupte argumentum est, at usu eleifend senserit. Decore feugait philosophia ne vel. Novum dissentiunt vis no, prompta definitiones vis at. Integre malorum eu est, quot numquam ad est."
			],
			lsnDur:[
			"31:06", "35:41", "07:21", "47:21", "40:50", "46:19", "40:17", "23:57", "44:54", "12:41", "57:35", "23:50", "43:24", "01:42", "58:09", "12:35", "04:02", "14:44", "51:01", "30:41", "38:19", "52:14", "20:04", "39:02", "41:46", "11:59", "36:45", "32:12", "10:17", "47:29", "49:30"
			]
		},
		block = {
			name:"Course Name 4",
			//9 lessons
			lsnNames:[
			"Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu."
			],
			lsnDur:[
			"37:59", "45:22", "19:29", "10:30", "26:38", "50:06", "47:15", "45:56", "12:54"
			]
		},
		block = {
			name:"Course Name 5",
			//18 lessons
			lsnNames:[
			"Aliquam aliquet vehicula enim", "Sodales malesuada", "Etiam scelerisque efficitur est", "Aenean faucibus consequat", "Nunc eu ultricies", "Aenean in tellus ut lacus", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu.",
				"Pri no unum soleat, te corpora pericula pri, falli voluptua percipit his id. Vis ea ullum expetenda, ad assentior honestatis vel. Vel ne homero dissentiet vituperatoribus, nam ex ancillae assentior vulputate. Facilis docendi adipiscing usu id, epicuri legendos instructior id vis. Vix ex utinam noster, ut qui ipsum nominavi, tale dicit quo eu.",
				"Omnes dictas nam id, in ius tempor placerat definitionem, ex vis intellegebat definitionem. Vel sint maluisset ne, usu cu mundi pericula, has ei impedit ceteros. Sea tempor aliquid officiis at, omnium admodum neglegentur vis ei. Ei propriae prodesset mea, ne eum liberavisse conclusionemque. Luptatum dignissim omittantur et his, ignota repudiare ex mei.",
				"Te omnes deserunt quo, nec id graece alterum. Nec modus doming ut. An pro nominavi noluisse democritum, amet maiorum convenire an has. Partem nostrum intellegebat vel eu.",
				"Ei laudem quodsi quo, sit ut oblique malorum scribentur. Eu ferri dolorum est. Ei cum dico molestiae, no mentitum ocurreret vim, ea per epicuri placerat antiopam. Et tota expetenda efficiantur vim, ne adhuc error duo, soleat eripuit te sea. Vix deleniti lucilius detraxit te, ut summo nonumes vel, eu mea graecis scaevola. Eu sed autem vituperata, per ne malis nostrum.",
				"Ex tation complectitur pro. Ei per perfecto ocurreret. Suas cetero fabellas ad cum, vim ei imperdiet reformidans, id latine tractatos his. Ea quo denique nominati, sed at ullum probatus evertitur. Dicam possim prompta cu vim, quis habeo disputando duo ad, rationibus consequuntur ex mei.",
				"Vix ut impetus petentium accusamus, atqui facilis mea cu. Duo ut splendide scriptorem, at omnis affert mel, ut cum vidit euismod. Vim cu quot ceteros, ad mei liber maiorum. Ex suscipit laboramus suscipiantur cum, qui saepe consulatu ne, eos no veri fabellas. Ei eam probo ocurreret mediocritatem, ea duo purto porro. Te pro errem postulant, per eirmod vidisse at. In eos tamquam malorum.",
				"Mea dicit percipit at, animal volumus mei ex. Id sale aeterno omnesque pri, ut qui legere graeco aperiam. At has reque tamquam. Pri no velit propriae luptatum. Odio legendos ei pri, ex sit quando persecuti.",
				"Illum fuisset ut mei. Vim at debet viderer nusquam, vel soleat intellegat assueverit an. Id duo facilis voluptua corrumpit. Nec ne appareat pertinax, mel utamur consulatu cu. Has an eruditi posidonium referrentur, ut etiam mucius omittam usu, cu partem dictas feugait vim. Alia possit labitur eu mea. Per soleat apeirian eu, mutat cotidieque ne pro, mutat ignota imperdiet eos te.",
				"At est duis imperdiet. An per recusabo assueverit, iriure invenire ea pri. Ad mea platonem repudiare, ad omnes oratio eam. Vix eu atomorum periculis. In vocent disputationi vim, ne integre phaedrum eum. Eu posse urbanitas vix, sea eu movet aeterno."
			],
			lsnDur:[
			"03:51", "24:56", "31:56", "29:02", "12:53", "31:29", "45:03", "56:59", "01:50", "21:11", "37:02", "09:55", "54:45", "14:01", "22:03", "50:35", "49:13", "10:43"
			]
		},
		block = {
			name:"Course Name 6",
			//5 lessons
			lsnNames:[
			"Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius."
			],
			lsnDur:[
			"39:03", "08:39", "55:10", "55:56", "54:18"
			]
		},
		block = {
			name:"Course Name 7",
			//36 lessons
			lsnNames:[
			"Lorem ipsum dolor", "Sit amet", "Consectetur adipiscing elit", "Aliquam aliquet vehicula enim", "Sodales malesuada", "Etiam scelerisque efficitur est", "Aenean faucibus consequat", "Nunc eu ultricies", "Aenean in tellus ut lacus", "Aenean faucibus consequat", "Nunc eu ultricies", "Aenean in tellus ut lacus", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales", "Interdum viverra quis in odio", "Pellentesque finibus", "Egestas urna", "Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu.",
				"Pri no unum soleat, te corpora pericula pri, falli voluptua percipit his id. Vis ea ullum expetenda, ad assentior honestatis vel. Vel ne homero dissentiet vituperatoribus, nam ex ancillae assentior vulputate. Facilis docendi adipiscing usu id, epicuri legendos instructior id vis. Vix ex utinam noster, ut qui ipsum nominavi, tale dicit quo eu.",
				"Omnes dictas nam id, in ius tempor placerat definitionem, ex vis intellegebat definitionem. Vel sint maluisset ne, usu cu mundi pericula, has ei impedit ceteros. Sea tempor aliquid officiis at, omnium admodum neglegentur vis ei. Ei propriae prodesset mea, ne eum liberavisse conclusionemque. Luptatum dignissim omittantur et his, ignota repudiare ex mei.",
				"Te omnes deserunt quo, nec id graece alterum. Nec modus doming ut. An pro nominavi noluisse democritum, amet maiorum convenire an has. Partem nostrum intellegebat vel eu.",
				"Ei laudem quodsi quo, sit ut oblique malorum scribentur. Eu ferri dolorum est. Ei cum dico molestiae, no mentitum ocurreret vim, ea per epicuri placerat antiopam. Et tota expetenda efficiantur vim, ne adhuc error duo, soleat eripuit te sea. Vix deleniti lucilius detraxit te, ut summo nonumes vel, eu mea graecis scaevola. Eu sed autem vituperata, per ne malis nostrum.",
				"Ex tation complectitur pro. Ei per perfecto ocurreret. Suas cetero fabellas ad cum, vim ei imperdiet reformidans, id latine tractatos his. Ea quo denique nominati, sed at ullum probatus evertitur. Dicam possim prompta cu vim, quis habeo disputando duo ad, rationibus consequuntur ex mei.",
				"Vix ut impetus petentium accusamus, atqui facilis mea cu. Duo ut splendide scriptorem, at omnis affert mel, ut cum vidit euismod. Vim cu quot ceteros, ad mei liber maiorum. Ex suscipit laboramus suscipiantur cum, qui saepe consulatu ne, eos no veri fabellas. Ei eam probo ocurreret mediocritatem, ea duo purto porro. Te pro errem postulant, per eirmod vidisse at. In eos tamquam malorum.",
				"Mea dicit percipit at, animal volumus mei ex. Id sale aeterno omnesque pri, ut qui legere graeco aperiam. At has reque tamquam. Pri no velit propriae luptatum. Odio legendos ei pri, ex sit quando persecuti.",
				"Illum fuisset ut mei. Vim at debet viderer nusquam, vel soleat intellegat assueverit an. Id duo facilis voluptua corrumpit. Nec ne appareat pertinax, mel utamur consulatu cu. Has an eruditi posidonium referrentur, ut etiam mucius omittam usu, cu partem dictas feugait vim. Alia possit labitur eu mea. Per soleat apeirian eu, mutat cotidieque ne pro, mutat ignota imperdiet eos te.",
				"At est duis imperdiet. An per recusabo assueverit, iriure invenire ea pri. Ad mea platonem repudiare, ad omnes oratio eam. Vix eu atomorum periculis. In vocent disputationi vim, ne integre phaedrum eum. Eu posse urbanitas vix, sea eu movet aeterno.",
				"Eum et molestiae dissentiunt, sit ignota doming viderer ne. Autem maiorum fuisset pri te. Voluptua maiestatis ad sit, purto reprehendunt ex vis. Munere eruditi philosophia quo no.",
				"Cu solet oblique ornatus vim, has etiam malorum noluisse ut, an mea soluta fierent facilisi. No rebum fugit democritum mei, et autem tation ceteros sea, mollis qualisque sed eu. Ut has stet graeco, id cum nobis clita, albucius convenire nam eu. No eam lorem mucius perfecto, ad sed quis wisi labore. Eos paulo repudiandae te. Ne voluptaria ullamcorper pri, graeci accusamus liberavisse ius ut. Copiosae percipit lobortis ex sea, virtute adolescens eum ad.",
				"Lorem ipsum dolor sit amet, eos putant viderer atomorum in, usu erat etiam ei, his an magna choro. Probo antiopam id pro, at probo cotidieque ullamcorper vis. No facilis invenire aliquando duo, dicit eligendi delicata eu sit. Ea laudem soluta praesent his, pri magna petentium ei, ex qui nibh copiosae scribentur. In cum labitur sensibus, vel habeo prompta ne, mei cu nostrum salutatus.",
				"Ad pri molestiae mediocritatem, ponderum scripserit appellantur ad vis. His duis inani facilisis ne, commodo maiestatis vix ei. Pro ut similique omittantur, quem placerat phaedrum mel ex, primis oportere vix eu. Vix nostrum democritum at, cu pri aliquando assueverit dissentiunt, etiam conceptam abhorreant ad nam. Vidit volutpat eam ex, ei nam nihil vocent admodum, in duo affert deleniti probatus.",
				"Qui ut unum posidonium, ad admodum albucius sententiae est. Mel ad paulo minimum, mei ad nonumy instructior. Per molestiae efficiendi ea. Cu eos nonumes conclusionemque, his dolores inciderint ad.",
				"Vim atqui iuvaret et, vel debet nihil ut. Sed ceteros mandamus ne, sit alii soluta noluisse at. Mei cu iusto tamquam. Cu nam adhuc diceret, volutpat incorrupte qui at. Te nec eripuit principes consequat. Facer ornatus quo no, diam impedit sea te.",
				"No regione tincidunt nec. Soleat nusquam mel an, sed assum dicam postulant in, ei mei affert iuvaret percipit. Ignota vocibus reprehendunt has id, vix brute labore neglegentur at. Cu eos dolor dolorum philosophia. Id duis saperet usu, reque sonet sea te, no his case equidem. Ut porro expetenda per, alienum iudicabit eu qui. Et exerci possit aperiam mel.",
				"Est mazim urbanitas posidonium cu, est in libris postulant. Saepe persecuti definitionem sit te, fuisset evertitur ex vim, cu autem percipitur sed. Solet minimum te nec, no quod delenit consulatu his. Ex sed feugait gloriatur, graeco epicuri mediocrem an eam. Ut delectus aliquando mnesarchum mel, dolore sanctus disputando qui at. Et has option officiis aliquando, no per patrioque percipitur intellegebat. Hinc instructior ex duo.",
				"Imperdiet posidonium repudiandae eos ea, vim ne quis adipisci disputando. Usu graece virtute ocurreret te. Nec dolor vocibus adipiscing at. Et qui posse nostro. Animal scripta copiosae mea ad, cum ut vitae alterum, ea mei solet labore dissentiet.",
				"Laudem postea et est. Eos veniam equidem eligendi id, sit at ridens iisque philosophia. Mentitum omnesque antiopam his an, debitis quaestio percipitur duo no, alii probo per id. Sed cu eius minimum, ad clita malorum similique eum. No mel cetero expetenda, eius atomorum his cu. Atomorum mandamus postulant sit eu.",
				"Eum iriure albucius cu, ut esse nostrum quo, est diam omnes no. Eu laoreet incorrupte argumentum est, at usu eleifend senserit. Decore feugait philosophia ne vel. Novum dissentiunt vis no, prompta definitiones vis at. Integre malorum eu est, quot numquam ad est.",
				"Viderer salutatus consequat duo cu, nec timeam interesset id. Ut laoreet maiestatis definitiones est, sit adipiscing cotidieque repudiandae ea. Copiosae principes signiferumque ad ius, nec ei detracto percipit constituto. Has te etiam saepe signiferumque. Ex eos salutandi patrioque.",
				"In sea unum debitis torquatos, sea et repudiare neglegentur. Intellegam assueverit eam te. Usu ea verear inermis, ignota pertinacia et nec. Detracto principes an vis. Vulputate persequeris mea at, tota dicit reprimique est ea.",
				"An pro etiam aeque feugiat, quas saepe omittantur est eu. Ne nihil nemore has, feugiat voluptua adolescens eu nam, sit in mazim corrumpit accommodare. Tota expetenda sed ad, cu mea mandamus honestatis. Id nec offendit appareat, vidit pericula appellantur sit ea. Graeco docendi mel te.",
				"Qui ignota scaevola volutpat id, an solum mediocrem intellegam vis. Eos id oportere maluisset. Fastidii forensibus scribentur in cum, eu cum virtute instructior, fabulas eleifend prodesset ut quo. An veri minim democritum usu, ea vis voluptua tractatos.",
				"Ne recusabo indoctum mel, mea veri solum ea. Tota invidunt petentium ea qui, qui debet libris praesent cu. Munere antiopam expetenda vix ex, integre discere nominavi vis id. Ex atqui indoctum splendide eum, te vim ceteros legendos recteque, ad mel populo eruditi petentium.",
				"Ne sonet dissentias vel, quod vidit ne vis, his mollis timeam te. Ne cum dicta volutpat percipitur. Solet inermis sententiae ea mel, eos ei eius lobortis indoctum, nam no debet laoreet. Graecis definitiones te eos, ne dicta forensibus referrentur sea, qui ad errem putent conceptam.",
				"Adipisci nominati mandamus at per, an vis tantas causae. At mei quas periculis hendrerit, illum option comprehensam qui ei, vituperata instructior cu ius. Diam qualisque in pro. Ei eruditi ceteros usu. Vix dictas nostrud fabulas an, debet consetetur id pro. Indoctum instructior ad mei, quo at omnes recteque, pri essent alterum complectitur ex.",
				"In vis iusto aeterno. An his ullum labore expetendis, has exerci maiestatis ea, eirmod admodum intellegebat vel eu. Eligendi delectus deterruisset ex vis, te detraxit ocurreret usu. Ut nec possit democritum, et quo unum salutatus euripidis, utinam alterum comprehensam usu ad.",
				"Eos erat neglegentur ut, modo meliore eam ne. Eam dicta oblique salutandi ne, facer utinam voluptatum cu vis. Vis eu labitur accusata democritum. Sit hinc fabulas delicata cu, an illud tempor putent qui. Veniam iriure prompta cum an, erat disputando in nec. Ut his aliquip verterem, quo et scripta maiorum officiis.",
				"Congue ridens instructior no vix, eu eos quando senserit. Vis id suas luptatum elaboraret, ne legere aliquid appetere sed. Verear deterruisset ne his. Ei has solum quodsi equidem, mel esse placerat ad.",
				"Usu ea paulo intellegat, audiam hendrerit interesset ei mei, qui eu tibique delectus consulatu. Ei eam cetero option voluptaria. Ius id apeirian assentior, ei nisl persequeris mei. Eu mea illud honestatis, vis eu euismod vivendo, essent civibus pro no."
			],
			lsnDur:[
			"59:10", "42:37", "48:49", "45:50", "34:16", "41:08", "36:43", "16:16", "27:24", "54:18", "32:31", "46:17", "58:48", "25:06", "57:40", "16:40", "53:08", "51:34", "54:50", "58:24", "22:52", "41:02", "01:41", "05:08", "43:20", "04:55", "17:21", "38:38", "33:13", "31:14", "53:30", "05:25", "46:21", "05:40", "01:18", "54:04"
			]
		},
		block = {
			name:"Course Name 8",
			//9 lessons
			lsnNames:[
			"Donec vitae urna ut arcu",  "Gravida vehicula sed eu ipsum", "Maecenas consequat ornare", "Risus non ultrices", "Mauris neque tortor", "Facilisis at vestibulum eget", "Mollis ut turpis", "Donec in nulla", "Ac quam rutrum sodales"
			],
			lsnDescr:[
				"Lorem ipsum dolor sit amet, mazim dicant vocent qui ad, mel utinam sapientem ea. His suas mundi impedit te, qui cu clita fuisset salutandi. Sit ei nulla harum. Sit evertitur intellegebat ea, ex lorem labore deleniti pro, nam at minimum accusam nominavi. Idque delicata per an.",
				"At mea ubique ignota. Ne quod patrioque voluptatibus cum, nam cu possit voluptua. Cu per diam wisi forensibus, ei est scripta nominavi. Ea sea magna maiorum civibus. In est utinam dicunt salutatus, ea postea menandri sea, mei ne explicari vituperatoribus. Error timeam quaeque cu nam, intellegam concludaturque conclusionemque ut cum, dolorum vituperatoribus vim ad.",
				"Per ut minim veniam, eam eu putant sapientem. No elitr tollit reprehendunt mel. Vis ei quod odio efficiantur, ea choro mucius tritani sed. An pro graeci eripuit ocurreret, id sea purto equidem, alii ridens dolores no vix. Eu persius sapientem sed. Nam adhuc fabulas te, ocurreret theophrastus ea mei.",
				"Consul phaedrum definitiones mel ne, eum honestatis inciderint no. In solum alterum per. Te ridens impedit mea. His quodsi explicari cu, ne ullum abhorreant contentiones mei. Suavitate democritum duo ut, cum ipsum pericula ex.",
				"Saperet admodum no vel, est officiis nominati te. In vel oratio inermis, pro ut assentior adipiscing. Te nulla tamquam recusabo vim, ad duo mucius malorum consetetur, sea summo maiestatis elaboraret no. Pri in facilisi dignissim, eum persius scribentur ne, sed ei alterum fabellas facilisis. Sea ad vidit idque, et liber hendrerit quo. Eos ridens ceteros ad, eu eam nonumy fierent, at sed nibh dicit mucius.",
				"His eu viris tantas tractatos, quo et harum aperiri gubergren. Imperdiet constituam efficiantur no vel, ei vidit saperet recteque nam. Pro at utamur deseruisse. An quo dignissim constituto voluptatibus, eu magna verear malorum duo, ut debitis blandit dissentiet qui. Dictas atomorum ocurreret id mel. Mei utamur imperdiet et.",
				"In mei fabulas dolorum molestie, munere necessitatibus ut sit. Ex debet zril graeco sea. In pri reque indoctum deseruisse, justo mazim persius no sed. In est tota ubique constituam.",
				"Ex sea intellegat abhorreant. Ut vel animal fabulas, atqui dolor necessitatibus te usu, pro sumo graecis eu. Graeci doming omnesque ea est, ius ex dolor exerci. Has et sonet saepe, vocent expetenda intellegam ad pri.",
				"Cu reformidans reprehendunt per, ex urbanitas elaboraret mea. Vitae oportere in usu, pri duis detraxit ex. Nec te integre verterem. Choro doming complectitur his at, dictas officiis prodesset mel at. Antiopam patrioque at sea, tractatos quaerendum sed eu, magna ubique eum cu."
			],
			lsnDur:[
			"50:54", "28:06", "11:37", "19:02", "46:07", "48:47", "27:21", "11:45", "51:46"
			]
		}
	]
}